### ISSUE TITLE
pip install fails with IOError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by nbeaver** [mdipierro/buckingham#3]
Full backtrace:

```
------------------------------------------------------------
/usr/bin/pip run on Wed Jan 27 20:39:11 2016
Downloading/unpacking buckingham
  Getting page https://pypi.python.org/simple/buckingham/
  URLs to search for versions for buckingham:
  * https://pypi.python.org/simple/buckingham/
  Analyzing links from page https://pypi.python.org/simple/buckingham/
    Found link https://pypi.python.org/packages/source/b/buckingham/buckingham-0.1.tar.gz#md5=c941019f7f0f554b94fe8168af0525fe (from https://pypi.python.org/simple/buckingham/), version: 0.1
  Downloading buckingham-0.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/b/buckingham/buckingham-0.1.tar.gz#md5=c941019f7f0f554b94fe8168af0525fe (from https://pypi.python.org/simple/buckingham/)
  Running setup.py (path:/tmp/pip-build-L9zFtd/buckingham/setup.py) egg_info for package buckingham
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-L9zFtd/buckingham/setup.py", line 10, in <module>
        long_description=open("README.md").read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-L9zFtd/buckingham/setup.py", line 10, in <module>

    long_description=open("README.md").read(),

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-L9zFtd/buckingham
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-L9zFtd/buckingham
```

**Comment by mdipierro** [comment]
I must have something wrong in setup.py. the READE.md file does not apper to be in egg. Not sure. Will look into it asap. sorry.

**Comment by zbeekman** [comment]
same issue for me

**Comment by nitintt1991** [comment]
I faced the same issue while installing a package. Any help?

**Comment by abusizhishen** [comment]
i also faced this issue and need help

**Comment by mdipierro** [comment]
Sorry. Will fix asap.

**Comment by AndrewChap** [comment]
This works for me:
pip install git+git://github.com/mdipierro/buckingham.git

However, this module does not appear to work in python3.6.  Trying [pint](https://github.com/hgrecco/pint) in the meantime...

**Comment by Phader** [comment]
Can confirm this issue persists. Will update with a workaround if i find one.
